version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "scan latest"
          command: |
            docker scan bethdevopsbunny/podchaosmonkey:latest --accept-license
      - run:
          name: "build container"
          command: |
                docker login -u bethdevopsbunny -p $DOCKER_PASS
                docker build . --tag bethdevopsbunny/podchaosmonkey:$CIRCLE_SHA1
                docker push bethdevopsbunny/podchaosmonkey:$CIRCLE_SHA1

            


workflows:
  build-workflow:
    jobs:
      - build
