version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "scan latest"
          command: |
            docker login -u bethdevopsbunny -p $DOCKER_PASS
            docker scan bethdevopsbunny/podchaosmonkey:latest --accept-license --json >> OLDIMAGEJSON
      - run:
          name: "build container"
          command: |
                docker build . --tag bethdevopsbunny/podchaosmonkey:$CIRCLE_SHA1
                docker scan bethdevopsbunny/podchaosmonkey:$CIRCLE_SHA1 --accept-license --json >> NEWIMAGEJSON

      - run:
          name: "compare container vulnerabilities"
          command: |
                DIFF=$(echo OLDIMAGEJSON | jq .uniqueCount - echo NEWIMAGEJSON | jq .uniqueCount)
                echo $DIFF

      - run:
          name: "push container"
          command: |
              docker push bethdevopsbunny/podchaosmonkey:$CIRCLE_SHA1

            


workflows:
  build-workflow:
    jobs:
      - build
